-- ============================================================================
-- Miura · Datos semilla (seed)
-- ----------------------------------------------------------------------------
-- Intencionalmente SIN datos de negocio.
--
-- Cada carnicería construye su propio catálogo desde la app:
--   · Proveedores  → panel admin › Proveedores
--   · Productos    → panel admin › Configuración (Productos)
--
-- Los usuarios NO se crean aquí (insertarlos a mano en auth.users por SQL deja
-- filas incompletas que rompen el login de Supabase). El primer admin se crea
-- con `node scripts/seed-users.mjs` usando la API oficial de administración.
--
-- La app arranca perfectamente con la base vacía: no hay ningún dato semilla
-- necesario para su funcionamiento.
-- ============================================================================
